# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Automation test runner

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8 
    - name: Get tests
      uses: actions/checkout@main
      with:
        repository: Bidnij/ComplyCloudAutomationTest
        ref: refs/heads/master  
        path: ComplyCloudAutomationTest
    - name: Grant execute permission for gradlew
      working-directory: ComplyCloudAutomationTest
      run: chmod +x gradlew   
    - name: Run Test
      working-directory: ComplyCloudAutomationTest
      run: ./gradlew clean test
#       shell: bash
#     - name: Install Google Chrome # Using shell script to install Google Chrome
#       run: |
#        chmod +x ./scripts/InstallChrome.sh
#         ./scripts/InstallChrome.sh

#   - name: Build with Gradle
#       run: ./gradlew test

