# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Automation test runner

on:
  push:
    branches:
      - staging

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8 
    - name: Get tests
      uses: actions/checkout@main
      with:
        repository: Bidnij/ComplyCloudAutomationTest
        ref: refs/heads/master
        token: ${{ secrets.COMPLYCLOUDAUTOMATIONTEST }}
        path: ComplyCloudAutomationTest
    - name: Grant execute permission for gradlew
      working-directory: ComplyCloudAutomationTest
      run: chmod +x gradlew   
    - name: Run Test
      working-directory: ComplyCloudAutomationTest
      run: |
        ./gradlew clean test
        ls -la
        ./.allure/allure-2.2.1/bin/allure generate --clean
    - name: getAllure results
      uses: actions/checkout@main  
      with:
        ref: gh-pages 
        path: ComplyCloudAutomationTest/gh-pages
    - name: gitConfig
      working-directory: ComplyCloudAutomationTest/gh-pages
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        ls -la ../
        echo "======="
        ls -la ../build/allure-results
#        git commit -m "Add changes" -a
#     - name: Push changes
#       uses: ad-m/github-push-action@master
#       with:
#         github_token: "IdDjc7l$1isJnt78Kq*OW$1Y"
#         branch: "main"
#         directory: build/allure-results

#       shell: bash
#     - name: Install Google Chrome # Using shell script to install Google Chrome
#       run: |
#        chmod +x ./scripts/InstallChrome.sh
#         ./scripts/InstallChrome.sh



#   - name: Build with Gradle
#       run: ./gradlew test

