# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Automation test runner

on:
  push:
    branches:
      - staging

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8 
    - name: Get tests
      uses: actions/checkout@main
      with:
        repository: Bidnij/ComplyCloudAutomationTest
        ref: refs/heads/master
        token: ${{ secrets.COMPLYCLOUDAUTOMATIONTEST }}
        path: ComplyCloudAutomationTest
    - name: Grant execute permission for gradlew
      working-directory: ComplyCloudAutomationTest
      run: chmod +x gradlew   
    - name: Run Test
      working-directory: ComplyCloudAutomationTest
      run: |
        HOMEBREW_NO_INSTALL_CLEANUP=1 brew install allure
        ./gradlew clean test
        allure generate --clean ./build/allure-results
    - name: getAllure results
      uses: actions/checkout@main  
      with:
        ref: gh-pages 
        path: ComplyCloudAutomationTest/gh-pages
    - name: gitConfig and obtain files
      working-directory: ComplyCloudAutomationTest/gh-pages
      run: |
        cp -R ../allure-report/* ./
    - name: Deploy pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.COMPLYCLOUDAUTOMATIONTEST }}
        publish_dir: ./ComplyCloudAutomationTest/gh-pages
    
    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Allure results

        body: "You can check results here: https://bidnij.github.io/TestRunGitHub"
        to: mbi@compent.net
        from: unnamed1352@gmail.com
