# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Run project test

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew    
    - name: Get tests
      uses: actions/checkout@master
      with:
        name: Bidnij/ComplyCloudAutomationTest
        ref: refs/heads/master  
    - name: Check 
      run: |
        pwd;
        ls -la;
        echo "!!!!!!!!!!!!!!!!!!!!!!";
        ls -la ../;
            
#     - name: Run Test
#       run: chmod +x ./scripts/runtests.sh
#       shell: bash
#     - name: Install Google Chrome # Using shell script to install Google Chrome
#       run: |
#        chmod +x ./scripts/InstallChrome.sh
#         ./scripts/InstallChrome.sh

#   - name: Build with Gradle
#       run: ./gradlew test

